/// Flutter icons CustomIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {

  static const _kFontFam = 'CustomIcon';
  // static final String _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData main = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData diets_1 = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData pin = IconData(0xe803, fontFamily: _kFontFam);
}
